version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5432:5432'

  node:
    image: node:16
    container_name: case-xp
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://prisma:prisma@postgres:5432/case_xp_back_end
      TOKEN_SECRET: mySecret

networks:
  default:
    name: case-xp
