on: push

jobs:
  Lint_and_Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Installing dependencies
        run: npm ci

      - name: Running eslint
        run: npm run lint
